# Generated by Django 3.2 on 2022-06-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Main.extension', verbose_name='Extension'),
            preserve_default=False,
        ),
    ]
