# Generated by Django 3.2 on 2022-06-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='link',
            field=models.URLField(default=None, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='score',
            field=models.IntegerField(default=None, verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(default=None, max_length=100, verbose_name='Severity'),
            preserve_default=False,
        ),
    ]
