# Generated by Django 3.2 on 2022-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_group_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='_Main_extension_groups_+', to='Main.Group', verbose_name='Group(s)'),
        ),
    ]
