# Generated by Django 3.2 on 2022-06-04 19:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220604_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
