# Generated by Django 3.2 on 2022-06-02 14:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_extension_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='_Main_asset_softwares_+', to='Main.Software', verbose_name='Softwares'),
        ),
        migrations.AlterField(
            model_name='group',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='_Main_group_assets_+', to='Main.Asset', verbose_name='Assets'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name', 'version', 'asset'), unique=True, verbose_name='Slug')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Main.software', verbose_name='Software')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='software',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='_Main_software_vulnerabilities_+', to='Main.Vulnerability', verbose_name='Vulnerabilities'),
        ),
    ]
